
name: "Build fab files for MCU breakout"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '**.kicad_sch' # fix
      - '**.kicad_pcb'
      - '.github/workflows/kibot_fab.yml'
      - 'bin/fab.kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/kibot_fab.yml'
  workflow_dispatch:
  repository_dispatch: # remove?
    types: [run_qs]

env:
  BOARD: Dactyl MCU Breakout
  SHORT_NAME: hill_breakout

jobs:
  generate_fab_files:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:latest

    steps:
      # Everything should happend in kicad/
      # with output going into kicad/kibot_output/

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create PCBA and position folders with write access
        run: |
          cd kicad
          #mkdir pcba
          mkdir kibot_output
          pwd
          ls -la

      - name: Run KiBot
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: ./bin/fab.kibot.yml
          dir: ./kicad/kibot_output
          schema: ./kicad/${{ env.BOARD}}/${{ env.BOARD}}.kicad_sch
          board: ./kicad/${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          verbose: 1

      - name: Upload outputs Gerber zip, BOM, position
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SHORT_NAME }}-gerber-and-pcba
          path: |
            ./kicad/kibot_output/*


      ####
      # Logs
      #
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          cd kicad
          pwd
          ls -la
          cd kibot_output
          pwd
          ls -la 

      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SHORT_NAME }}_logs_fab
          path: |
            ./kicad/kibot_output/*.log
            ./kicad/kibot_output/*.txt
            ./kicad/kibot_output/*.html
